Update to emacs git (2017-02-14), happy this day. ;)

diff --git a/emacs-git/build-aux/gitlog-to-emacslog b/emacs-git/build-aux/gitlog-to-emacslog
--- a/emacs-git/build-aux/gitlog-to-emacslog
+++ b/emacs-git/build-aux/gitlog-to-emacslog
@@ -2,7 +2,7 @@
 
 # Convert git log output to ChangeLog format for GNU Emacs.
 
-# Copyright (C) 2014-2015 Free Software Foundation, Inc.
+# Copyright (C) 2014-2017 Free Software Foundation, Inc.
 
 # Author: Paul Eggert
 
@@ -23,7 +23,8 @@ LC_ALL=C
 export LC_ALL
 
 # The newest revision that should not appear in the generated ChangeLog.
-gen_origin=d2c7e14ac3bd2b517d35a86255c28d5b6d779451
+gen_origin=
+
 force=
 output=ChangeLog
 nmax=2
@@ -34,34 +35,53 @@ while [ $# -gt 0 ]; do
       -f|--force) force=1 ;;
       -n|--nmax) nmax="$2"; shift ;;
       -o|--output) output="$2" ; shift ;;
-      *) echo "Unrecognized argument: $1" >&2; exit 1 ;;
+      *) printf '%s\n' "Unrecognized argument: $1" >&2; exit 1 ;;
   esac
   shift
 done
 
 if [ ! -f ChangeLog.$nmax ]; then
-    echo "Can't find ChangeLog.$nmax" >&2
-    echo "Must be run from the top source directory" >&2
+    printf '%s\n' "Can't find ChangeLog.$nmax" >&2
+    printf '%s\n' "Must be run from the top source directory" >&2
     exit 1
 fi
 
+# If not specified in the command line, get gen_origin from the existing
+# ChangeLog file.
+[ "$gen_origin" ] || {
+    gen_origin_line=`
+      grep -E '^commit [0-9a-f]+ [(]inclusive[)]' ChangeLog.$nmax
+    ` || {
+	printf '%s\n' "ChangeLog.$nmax lacks a 'commit ... (inclusive)' line" >&2
+	exit 1
+    }
+    set $gen_origin_line
+    gen_origin=$2
+}
+
+# Get the new value for gen_origin from the latest version in the repository.
+new_origin=`git log --pretty=format:%H 'HEAD^!'` || exit
+
 if [ -f "$output" ]; then
-    [ ! "$force" ] && echo "$output exists" >&2 && exit 1
+    [ ! "$force" ] && printf '%s\n' "$output exists" >&2 && exit 1
     rm -f "$output" || exit 1
 fi
 
 # If this is not a Git repository, just generate an empty ChangeLog.
-test -d .git || {
+test -e .git || {
   >"$output"
   exit
 }
 
 # Use Gnulib's packaged ChangeLog generator.
-./build-aux/gitlog-to-changelog --ignore-matching='^; ' \
-  --format='%B' \
-  "$gen_origin.." >"ChangeLog.tmp" || exit
+# Maybe we should skip all "Merge branch 'master'" messages.
+# See eg the cairo-related ones.
+./build-aux/gitlog-to-changelog \
+    --ignore-matching="^; |^Merge branch '[^']*' of git\.(savannah|sv)\.gnu\.org:/srv/git/emacs|^Merge remote-tracking branch '.*'$" \
+  --ignore-line='^; ' --format='%B' \
+  "$gen_origin..$new_origin" >"ChangeLog.tmp" || exit
 
-if test -s "ChangeLog.tmp"; then
+if test -e "ChangeLog.tmp"; then
 
   # Fix up bug references.
   # This would be better as eg a --transform option to gitlog-to-changelog,
@@ -79,7 +99,7 @@ if test -s "ChangeLog.tmp"; then
   `
   start_year=
   end_year=
-  for year in $years; do
+  for year in ${years:-`date +%Y`}; do
     : ${start_year:=$year}
     end_year=$year
   done
@@ -90,10 +110,19 @@ if test -s "ChangeLog.tmp"; then
     year_range=$start_year-$end_year
   fi
 
+  # Update gen_origin
+  if test "$gen_origin" != "$new_origin"; then
+      sed -n '
+        1i\
+
+        /^This file records repository revisions/p
+        s/^commit [0-9a-f]* (exclusive)/commit '"$gen_origin"' (exclusive)/p
+        s/^commit [0-9a-f]* (inclusive)/commit '"$new_origin"' (inclusive)/p
+      ' <ChangeLog.$nmax >>"ChangeLog.tmp" || exit
+  fi
+
   # Append a proper copyright notice.
   sed -n '
-    1i\
-
     /^See ChangeLog.[0-9]* for earlier/,${
        s/ChangeLog\.[0-9]*/ChangeLog.'$nmax'/
        s/\(Copyright[ (C)]*\)[0-9]*-[0-9]*/\1'"$year_range"'/
diff --git a/emacs-git/lib-src/rcs2log b/emacs-git/lib-src/rcs2log
--- a/emacs-git/lib-src/rcs2log
+++ b/emacs-git/lib-src/rcs2log
@@ -2,7 +2,7 @@
 
 # RCS to ChangeLog generator
 
-# Copyright (C) 1992-1998, 2001-2015 Free Software Foundation, Inc.
+# Copyright (C) 1992-1998, 2001-2017 Free Software Foundation, Inc.
 
 # Author: Paul Eggert <eggert@twinsun.com>
 
@@ -20,7 +20,7 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 
-Copyright='Copyright (C) 2015 Free Software Foundation, Inc.
+Copyright='Copyright (C) 2017 Free Software Foundation, Inc.
 This program comes with NO WARRANTY, to the extent permitted by law.
 You may redistribute copies of this program
 under the terms of the GNU General Public License.
@@ -130,7 +130,8 @@ do
 		case $1 in
 		-n)	case ${2?}${3?}${4?} in
 			*"$tab"* | *"$nl"*)
-				echo >&2 "$0: -n '$2' '$3' '$4': tabs, newlines not allowed"
+				printf '%s\n' >&2 \
+				  "$0: -n '$2' '$3' '$4': tabs, newlines not allowed"
 				exit 1;;
 			esac
 			login=$2
@@ -140,7 +141,7 @@ do
 			# If $2 is not tab-separated, use colon for separator.
 			case ${2?} in
 			*"$nl"*)
-				echo >&2 "$0: -u '$2': newlines not allowed"
+				printf '%s\n' >&2 "$0: -u '$2': newlines not allowed"
 				exit 1;;
 			*"$tab"*)
 				t=$tab;;
@@ -149,7 +150,7 @@ do
 			esac
 			case $2 in
 			*"$t"*"$t"*"$t"*)
-				echo >&2 "$0: -u '$2': too many fields"
+				printf '%s\n' >&2 "$0: -u '$2': too many fields"
 				exit 1;;
 			*"$t"*"$t"*)
 				uf="[^$t]*$t" # An unselected field, followed by a separator.
@@ -161,7 +162,7 @@ do
 					expr "X$2" : "$uf$uf$sf"
 				`;;
 			*)
-				echo >&2 "$0: -u '$2': not enough fields"
+				printf '%s\n' >&2 "$0: -u '$2': not enough fields"
 				exit 1;;
 			esac
 			shift;;
@@ -186,9 +187,9 @@ do
 	--version)
 		set $Id
 		rcs2logVersion=$3
-		echo >&2 "rcs2log (GNU Emacs) $rcs2logVersion$nl$Copyright"
+		printf '%s\n' >&2 "rcs2log (GNU Emacs) $rcs2logVersion$nl$Copyright"
 		exit 0;;
-	-*)	echo >&2 "Usage: $0 [OPTION]... [FILE ...]$nl$Help"
+	-*)	printf '%s\n' >&2 "Usage: $0 [OPTION]... [FILE ...]$nl$Help"
 		case $1 in
 		--help) exit 0;;
 		*) exit 1;;
@@ -303,7 +304,8 @@ case $rlogfile in
 			esac
 			if test ! -d "$repository"
 			then
-				echo >&2 "$0: $repository: bad repository (see CVS/Repository)"
+				printf '%s\n' >&2 \
+				  "$0: $repository: bad repository (see CVS/Repository)"
 				exit 1
 			fi
 			pository=$repository;;
@@ -330,7 +332,7 @@ case $rlogfile in
 				T?*)
 					rlog_options=-r`expr "$CVSTAG" : 'T\(.*\)'`;;
 				*)
-					echo >&2 "$0: invalid CVS/Tag"; exit 1;;
+					printf '%s\n' >&2 "$0: invalid CVS/Tag"; exit 1;;
 				esac
 			fi;;
 		esac
@@ -401,8 +403,8 @@ case $rlogfile in
 	esac
 
 	case $datearg in
-	?*) $rlog $rlog_options "$datearg" ${1+"$@"} >$rlogfile;;
-	'') $rlog $rlog_options ${1+"$@"} >$rlogfile;;
+	?*) $rlog $rlog_options "$datearg" "$@" >$rlogfile;;
+	'') $rlog $rlog_options "$@" >$rlogfile;;
 	esac || exit;;
 esac
 
@@ -414,7 +416,7 @@ sort $SORT_K_OPTIONS </dev/null 2>/dev/null || SORT_K_OPTIONS='+2 -4r +4 +0'
 
 
 # Get the full name of each author the logs mention, and set initialize_fullname
-# to awk code that initializes the `fullname' awk associative array.
+# to awk code that initializes the 'fullname' awk associative array.
 # Warning: foreign authors (i.e. not known in the passwd file) are mishandled;
 # you have to fix the resulting output by hand.
 
@@ -546,8 +548,8 @@ esac
 
 # Function to print a single log line.
 # We don't use awk functions, to stay compatible with old awk versions.
-# `Log' is the log message.
-# `files' contains the affected files.
+# 'Log' is the log message.
+# 'files' contains the affected files.
 printlogline='{
 
 	# Following the GNU coding standards, rewrite
@@ -587,7 +589,7 @@ printlogline='{
 	}
 }'
 
-# Pattern to match the `revision' line of rlog output.
+# Pattern to match the 'revision' line of rlog output.
 rlog_revision_pattern='^revision [0-9]+\.[0-9]+(\.[0-9]+\.[0-9]+)*(['"$tab"' ]+locked by: [^'"$tab"' $,.0-9:;@]*[^'"$tab"' $,:;@][^'"$tab"' $,.0-9:;@]*;)?['"$tab"' ]*$'
 
 case $hostname in
@@ -595,7 +597,7 @@ case $hostname in
 	hostname=`(
 		hostname || uname -n || uuname -l || cat /etc/whoami
 	) 2>/dev/null` || {
-		echo >&2 "$0: cannot deduce hostname"
+		printf '%s\n' >&2 "$0: cannot deduce hostname"
 		exit 1
 	}
 
diff --git a/emacs-git/make-dist b/emacs-git/make-dist
--- a/emacs-git/make-dist
+++ b/emacs-git/make-dist
@@ -1,7 +1,7 @@
 #!/bin/sh
 ### make-dist: create an Emacs distribution tar file from current srcdir
 
-## Copyright (C) 1995, 1997-1998, 2000-2015 Free Software Foundation,
+## Copyright (C) 1995, 1997-1998, 2000-2017 Free Software Foundation,
 ## Inc.
 
 ## This file is part of GNU Emacs.
@@ -53,6 +53,7 @@ default_gzip=gzip
 newer=""
 with_tests=no
 changelog=yes
+verbose=no
 
 while [ $# -gt 0 ]; do
   case "$1" in
@@ -100,7 +101,6 @@ while [ $# -gt 0 ]; do
       clean_up=yes
       make_tar=yes
       update=no
-      check=no
      ;;
 
     ## Include the test/ directory.
@@ -109,8 +109,12 @@ while [ $# -gt 0 ]; do
       with_tests=yes
      ;;
 
+    "--verbose")
+      verbose=yes
+     ;;
+
     "--help")
-      echo "Usage: ${progname} [options]"
+      printf '%s\n' "Usage: ${progname} [options]"
       echo ""
       echo "  --bzip2	use bzip2 instead of gzip"
       echo "  --clean-up	delete staging directories when done"
@@ -123,12 +127,13 @@ while [ $# -gt 0 ]; do
       echo "  --snapshot	same as --clean-up --no-update --tar --no-check"
       echo "  --tar		make a tar file"
       echo "  --tests	include the test/ directory"
+      echo "  --verbose		noisier output"
       echo ""
       exit 0
     ;;
 
     * )
-      echo "${progname}: Unrecognized argument: $1" >&2
+      printf '%s\n' "${progname}: Unrecognized argument: $1" >&2
       exit 1
     ;;
   esac
@@ -137,9 +142,9 @@ done
 
 ### Make sure we're running in the right place.
 if [ ! -d src -o ! -f src/lisp.h -o ! -d lisp -o ! -f lisp/subr.el ]; then
-  echo "${progname}: Can't find 'src/lisp.h' and 'lisp/subr.el'." >&2
-  echo "${progname} must be run in the top directory of the Emacs" >&2
-  echo "distribution tree.  cd to that directory and try again." >&2
+  printf '%s\n' "${progname}: Can't find 'src/lisp.h' and 'lisp/subr.el'." >&2
+  printf '%s\n' "${progname} must be run in the top directory of the Emacs" >&2
+  printf '%s\n' "distribution tree.  cd to that directory and try again." >&2
   exit 1
 fi
 
@@ -155,7 +160,7 @@ then
       /*) ;;
       *)
 	if [ ! -f "$EMACS" ]; then
-	  echo "$0: You must set the EMACS environment variable " \
+	  printf '%s\n' "$0: You must set the EMACS environment variable " \
 	       "to an absolute file name." 2>&1
 	  exit 1
 	fi;;
@@ -168,7 +173,8 @@ version=`
   sed -n 's/^AC_INIT(GNU Emacs,[	 ]*\([^	 ,)]*\).*/\1/p' <configure.ac
 ` || version=
 if [ ! "${version}" ]; then
-  echo "${progname}: can't find current Emacs version in './src/emacs.c'" >&2
+  printf '%s\n' \
+    "${progname}: can't find current Emacs version in './src/emacs.c'" >&2
   exit 1
 fi
 
@@ -195,7 +201,7 @@ fi
 ### Make sure the subdirectory is available.
 tempparent="make-dist.tmp.$$"
 if [ -d ${tempparent} ]; then
-  echo "${progname}: staging directory '${tempparent}' already exists.
+  printf '%s\n' "${progname}: staging directory '${tempparent}' already exists.
 Perhaps a previous invocation of '${progname}' failed to clean up after
 itself.  Check that directories whose names are of the form
 'make-dist.tmp.NNNNN' don't contain any important information, remove
@@ -204,6 +210,11 @@ them, and try again." >&2
 fi
 
 if [ $check = yes ]; then
+
+  echo "Sanity checking (use --no-check to disable this)..."
+
+  error=no
+
   ls -1 lisp/[a-zA-Z]*.el lisp/[a-z]*/[a-zA-Z0-9]*.el \
 	lisp/[a-z]*/[a-z]*/[a-zA-Z0-9]*.el \
 	lisp/[a-z]*/[a-z]*/[a-z]*/[a-zA-Z0-9]*.el > /tmp/el
@@ -217,6 +228,7 @@ if [ $check = yes ]; then
 
   bogosities=`comm -13 /tmp/elelc /tmp/elc`
   if [ x"${bogosities}" != x"" ]; then
+    error=yes
     echo "The following .elc files have no corresponding .el files:"
     echo "${bogosities}"
   fi
@@ -224,6 +236,19 @@ if [ $check = yes ]; then
   ### Check for .el files with no corresponding .elc file.
   sed 's/\.elc$/.el/' /tmp/elc > /tmp/elcel
   losers=`comm -23 /tmp/el /tmp/elcel`
+
+  bogosities=
+  while read elc; do
+      el=`echo $elc | sed 's/c$//'`
+      [ -e $el ] || continue
+      [ $elc -nt $el ] || bogosities="$bogosities $elc"
+  done < /tmp/elc
+
+  if [ x"${bogosities}" != x"" ]; then
+      error=yes
+      echo "The following .elc files are older than their .el files:"
+      echo "${bogosities}"
+  fi
 
   rm -f /tmp/el /tmp/elc /tmp/elcel /tmp/elelc
 
@@ -238,9 +263,45 @@ if [ $check = yes ]; then
 
   done
   if [ x"${bogosities}" != x"" ]; then
+    error=yes
     echo "The following .el files have no corresponding .elc files:"
     echo "${bogosities}"
   fi
+
+
+  ## This is only a crude check, eg it does not handle .info
+  ## files with multiple .texi source files.
+  find doc -name '*.texi' > /tmp/el
+
+  bogosities=
+  while read texi; do
+      info=`sed -n 's/^@setfilename //p' $texi | sed 's|.*info/||'`
+      [ x"${info}" != x"" ] || continue
+      info=info/$info
+      [ -e $info ] || continue
+      [ $info -nt $texi ] || bogosities="$bogosities $info"
+  done < /tmp/el
+
+  rm -f /tmp/el
+
+  if [ x"${bogosities}" != x"" ]; then
+    error=yes
+    echo "The following .info files are older than their .texi files:"
+    echo "${bogosities}"
+  fi
+
+  ## This exits with non-zero status if any .info files need
+  ## rebuilding.
+  if [ -e Makefile ]; then
+      echo "Checking to see if info files are up-to-date..."
+      make --question info || error=yes
+  fi
+
+  if [ $error = yes ]; then
+      echo "Failed checks" >&2
+      exit 1
+  fi
+
 fi
 
 if [ $update = yes ]; then
@@ -283,7 +344,7 @@ echo "Creating top directory: '${tempdir}'"
 mkdir ${tempdir}
 
 if [ "$changelog" = yes ]; then
-  if test -d .git; then
+  if test -e .git; then
     echo "Making top-level ChangeLog"
     make ChangeLog CHANGELOG=${tempdir}/ChangeLog || \
       { x=$?; echo "make ChangeLog FAILED (try --no-changelog?)" >&2; exit $x; }
@@ -300,7 +361,7 @@ echo "Making links to top-level files"
 ln INSTALL README BUGS ${tempdir}
 ln ChangeLog.*[0-9] Makefile.in autogen.sh configure configure.ac ${tempdir}
 ln config.bat make-dist .dir-locals.el ${tempdir}
-ln aclocal.m4 ${tempdir}
+ln aclocal.m4 CONTRIBUTE ${tempdir}
 
 echo "Creating subdirectories"
 for subdir in site-lisp \
@@ -310,7 +371,7 @@ for subdir in site-lisp \
 	      nt nt/inc nt/inc/sys nt/inc/arpa nt/inc/netinet nt/icons \
 	      `find etc lisp admin test -type d` \
 	      doc doc/emacs doc/misc doc/man doc/lispref doc/lispintro \
-	      info m4 msdos \
+	      info m4 modules modules/mod-test msdos \
 	      nextstep nextstep/templates \
 	      nextstep/Cocoa nextstep/Cocoa/Emacs.base \
 	      nextstep/Cocoa/Emacs.base/Contents \
@@ -322,14 +383,14 @@ do
 
   if [ "$with_tests" != "yes" ]; then
     case $subdir in
-        test*) continue ;;
+        test*|*/mod-test*) continue ;;
     esac
   fi
 
   ## site-lisp for in-place installs (?).
   [ "$subdir" = "site-lisp" ] || [ -d "$subdir" ] || \
       echo "WARNING: $subdir not found, making anyway"
-  echo "  ${tempdir}/${subdir}"
+  [ "$verbose" = "yes" ] && echo "  ${tempdir}/${subdir}"
   mkdir ${tempdir}/${subdir}
 done
 
@@ -338,7 +399,7 @@ files=`find lisp \( -name '*.el' -o -name '*.elc' -o -name 'ChangeLog*' \
  -o -name 'README' \)`
 
 ### Don't distribute site-init.el, site-load.el, or default.el.
-for file in lisp/Makefile.in lisp/makefile.w32-in $files; do
+for file in lisp/Makefile.in $files; do
   case $file in
     */site-init*|*/site-load*|*/default*) continue ;;
   esac
@@ -347,7 +408,6 @@ done
 
 echo "Making links to 'leim' and its subdirectories"
 (cd leim
- ln makefile.w32-in ../${tempdir}/leim
  ln ChangeLog.*[0-9] README ../${tempdir}/leim
  ln CXTERM-DIC/README CXTERM-DIC/*.tit ../${tempdir}/leim/CXTERM-DIC
  ln SKK-DIC/README SKK-DIC/SKK-JISYO.L ../${tempdir}/leim/SKK-DIC
@@ -362,7 +422,7 @@ echo "Making links to 'build-aux'"
  ln gitlog-to-changelog gitlog-to-emacslog ../${tempdir}/build-aux
  ln install-sh missing move-if-change ../${tempdir}/build-aux
  ln update-copyright update-subdirs ../${tempdir}/build-aux
- ln dir_top make-info-dir ../${tempdir}/build-aux)
+ ln dir_top make-info-dir ar-lib ../${tempdir}/build-aux)
 
 echo "Making links to 'build-aux/snippet'"
 (cd build-aux/snippet
@@ -377,7 +437,6 @@ echo "Making links to 'src'"
  ln [a-zA-Z]*.in ../${tempdir}/src
  ln deps.mk ../${tempdir}/src
  ln README ChangeLog.*[0-9] ../${tempdir}/src
- ln makefile.w32-in ../${tempdir}/src
  ln .gdbinit .dbxinit ../${tempdir}/src
  cd ../${tempdir}/src
  rm -f globals.h config.h epaths.h Makefile buildobj.h)
@@ -390,7 +449,7 @@ echo "Making links to 'lib'"
 (snippet_h=`(cd build-aux/snippet && ls *.h)`
  cd lib
  ln [a-zA-Z]*.[ch] ../${tempdir}/lib
- ln gnulib.mk Makefile.am Makefile.in makefile.w32-in ../${tempdir}/lib
+ ln gnulib.mk Makefile.am Makefile.in ../${tempdir}/lib
  cd ../${tempdir}/lib
  script='/[*]/d; s/\.in\.h$/.h/'
  rm -f `(echo "$snippet_h"; ls *.in.h) | sed "$script"`)
@@ -400,21 +459,32 @@ echo "Making links to 'lib-src'"
  ln [a-zA-Z]*.[ch] ../${tempdir}/lib-src
  ln ChangeLog.*[0-9] Makefile.in README ../${tempdir}/lib-src
  ln rcs2log ../${tempdir}/lib-src
- ln makefile.w32-in ../${tempdir}/lib-src
  ln update-game-score.exe.manifest ../${tempdir}/lib-src)
 
 echo "Making links to 'm4'"
 (cd m4
  ln *.m4 ../${tempdir}/m4)
 
+echo "Making links to 'modules'"
+(cd modules
+ ln *.py ../${tempdir}/modules
+ if [ "$with_tests" = "yes" ]; then
+   for f in `find mod-test -type f`; do
+       case $f in
+           *.log|*.o|*.so) continue ;;
+       esac
+       ln $f ../$tempdir/modules/$f
+   done
+ fi
+)
+
 echo "Making links to 'nt'"
 (cd nt
  ln emacs-x86.manifest emacs-x64.manifest ../${tempdir}/nt
- ln config.nt emacs-src.tags ../${tempdir}/nt
- ln nmake.defs gmake.defs subdirs.el [a-z]*.bat [a-z]*.[ch] ../${tempdir}/nt
- ln *.in gnulib.mk ../${tempdir}/nt
- ln mingw-cfg.site epaths.nt INSTALL.OLD ../${tempdir}/nt
- ln ChangeLog.*[0-9] INSTALL README README.W32 makefile.w32-in ../${tempdir}/nt)
+ ln [a-z]*.bat [a-z]*.[ch] ../${tempdir}/nt
+ ln *.in gnulib.mk gnulib-modules-to-delete.cfg ../${tempdir}/nt
+ ln mingw-cfg.site epaths.nt INSTALL.W64 ../${tempdir}/nt
+ ln ChangeLog.*[0-9] INSTALL README README.W32 ../${tempdir}/nt)
 
 echo "Making links to 'nt/inc' and its subdirectories"
 for f in `find nt/inc -type f -name '[a-z]*.h'`; do
@@ -500,23 +570,22 @@ ln `find info -type f -print` ${tempdir}/info
 
 echo "Making links to 'doc/emacs'"
 (cd doc/emacs
- ln *.texi *.in makefile.w32-in ChangeLog.*[0-9] ../../${tempdir}/doc/emacs)
+ ln *.texi *.in ChangeLog.*[0-9] ../../${tempdir}/doc/emacs)
 
 echo "Making links to 'doc/misc'"
 (cd doc/misc
- ln *.texi *.tex *.in makefile.w32-in gnus-news.el ChangeLog.*[0-9] \
+ ln *.texi *.tex *.in gnus-news.el ChangeLog.*[0-9] \
     ../../${tempdir}/doc/misc)
 
 echo "Making links to 'doc/lispref'"
 (cd doc/lispref
- ln *.texi *.in makefile.w32-in README ChangeLog.*[0-9] \
-    ../../${tempdir}/doc/lispref
+ ln *.texi *.in README ChangeLog.*[0-9] ../../${tempdir}/doc/lispref
  ln spellfile ../../${tempdir}/doc/lispref
  ln two-volume.make two-volume-cross-refs.txt ../../${tempdir}/doc/lispref)
 
 echo "Making links to 'doc/lispintro'"
 (cd doc/lispintro
- ln *.texi *.in makefile.w32-in *.eps *.pdf ../../${tempdir}/doc/lispintro
+ ln *.texi *.in *.eps *.pdf ../../${tempdir}/doc/lispintro
  ln README ChangeLog.*[0-9] ../../${tempdir}/doc/lispintro
  cd ../../${tempdir}/doc/lispintro)
 
@@ -535,7 +604,7 @@ for subdir in . etc leim lib lib-src lisp lwlib msdos nt src; do
 done
 
 if [ "${newer}" ]; then
-  echo "Removing files older than $newer"
+  printf '%s\n' "Removing files older than $newer"
   ## We remove .elc files unconditionally, on the theory that anyone picking
   ## up an incremental distribution already has a running Emacs to byte-compile
   ## them with.
@@ -549,8 +618,9 @@ find ${tempparent} \( -name '*~' -o -name '#*#' -o -name '.*ignore' -o -name '=*
 if [ "${make_tar}" = yes ]; then
   echo "Looking for $default_gzip"
   found=0
-  temppath=`echo $PATH | sed -e 's/^:/.:/' -e 's/::/:.:/g' -e 's/:$/:./' \
-     -e 's/:/ /g'`
+  temppath=`printf '%s\n' "$PATH" |
+    sed -e 's/^:/.:/' -e 's/::/:.:/g' -e 's/:$/:./' -e 's/:/ /g'
+  `
   for dir in ${temppath}; do
     [ -x ${dir}/$default_gzip ] || continue
     found=1; break
@@ -566,7 +636,10 @@ if [ "${make_tar}" = yes ]; then
        *)  gzip_extension= ;;
   esac
   echo "Creating tar file"
-  (cd ${tempparent} ; tar cvf - ${emacsname} ) \
+  taropt=
+  [ "$verbose" = "yes" ] && taropt=v
+
+  (cd ${tempparent} ; tar c${taropt}f - ${emacsname} ) \
     | ${default_gzip} \
     > ${emacsname}.tar${gzip_extension}
 fi
